language: node_js
node_js:
  - "6.1"

notifications:
  email: false

env:
  global:
    - secure: "o6p/S9Ix07nxqzJFsxvywAmhyyzlSHpGsygSGpvuVwPhuz9zX3TtFmwn1RAtLf9oa6yHCKLH8nGuCRJvjxCj4UzIoBKAz7lsUTfEQQHw7JekJ/No447cTVRIVwxB6RplppBzWtRizgevCL4uhqIK3mzz3W2SZdoHWBhk8VPLuot1LkZcgPIvEMYUCKFKJcs5tkXKMYY9u0+KixtoUfs9sifrPyoWKDdjuElbWHMVeV8/gOHyqIxg/6wSx6QiNB4S38cypFba4dWw7nkBZ6tAvR8ZMuJi/dE/ZbW8c8FGdPgjv0rEO6czuJuJl99+mHG7Jwg8CwH6xJ3jh5zlAwr6Ff5dy5ALQ7O1yNJ4JrtaNAPrs2I+Op5iqtBmmgd0++fKsl+V+1UoMyAnCJ1MCUKSgOq7MQH9o0DgayXUgz/2RXgSou5fkSz66TGQTmunqcvlQX1fe8v20dU74xQrzme/CRh2AewB70OlsSYVpUoitSssVX8EG/GzIc0vb2S52fuoqFgj995kb/A9/EHtgdyz1IkdoKEnYMNIzryBTv8om9EG34ay8CY9NFMgKv0aYSB+lSBQAY24o34TZGsQKMq5Apfe0Ys+aa+Temvt7v0K/NykhJfxS7/un+NabAqPVSmxAUoPaiqati3YX6kqZDN/heq84Utb+6dieKP9efWWXPQ="
